unstable_features = true
edition = "2021"

# comments
comment_width = 110
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true

# imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
reorder_imports = true

# strings
format_strings = false
max_width = 100
match_block_trailing_comma = true

format_code_in_doc_comments = true
format_macro_matchers = true
match_arm_leading_pipes = "Preserve"
reorder_impl_items = true
trailing_comma = "Vertical"
trailing_semicolon = true
